### ISSUE TITLE
Mistake in DietOjalgo.groovy

### ISSUE THREAD

**Issue by apete** [paulk-asert/groovy-constraint-programming#1]
Hi,

There is a mistake in [DietOjalgo.groovy](https://github.com/paulk-asert/groovy-constraint-programming/blob/master/subprojects/Diet/src/main/groovy/DietOjalgo.groovy) – there is no objective function defined. To fix it you have to do one of these things:

1. Add a weight to the "Cost" expression. In this particular case it can be set to anything non-zero. 1.0 is a good alternative.
2. Alternatively, in this case, it is possible to remove the "Cost" expression entirely, and instead add weights to each of the food item variables. Those weights would be 2.0, 3.5, 8.0... (the parameters from the "Cost" expression).

In ojAlgo the objective function is generated combining everything that has a "weight".

The way the example is now, the algorithm stops after finding a feasible solution, and reports the optimal value to be 0.0

**Comment by paulk-asert** [comment]
Thanks for your comment. I'll take a closer look. Here is the current output I get:
```
0 <= Cheese: 0.408139
0 <= Potato: 1.853879
0.5 <= Fish: 0.591623
0 <= Yogurt: 0
10 <= Carbohydrates: 42.060923
8 <= Fat: 8.0
Cost: 12.553784
Protein: 10.0 <= 10
300 <= Calories: 300.0

```

**Comment by apete** [comment]
That may be the correct optimal solution, I don't know, but if it is you're lucky. Since there is no objective function defined any feasible solution is optimal (the objective function is simply 0.0).

I found [your Groovy Constraint Programming slides](https://speakerdeck.com/paulk/groovy-constraint-programming?slide=37) and just happened to spot the omission. The easiest way to fix it is just to call `cost.weight(1.0)`.

**Comment by paulk-asert** [comment]
Yes, you are correct. I'll adjust the code shortly.

**Comment by paulk-asert** [comment]
Github repo updated. The slides will be updated next time I give the talk (in a couple of weeks as it turns out). Thanks for the feedback.

**Comment by paulk-asert** [comment]
Slides are now also updated:
https://speakerdeck.com/paulk/groovy-constraint-programming?slide=68
